### ISSUE TITLE
CoinShop signs seem broken, items don't rotate in frames 

### ISSUE THREAD

**Issue by SmallSansSerif** [DarkBlade12/ItemSlotMachine#11]
Getting errors in console.

https://pastebin.com/Z34Pme7M
https://pastebin.com/Psq2D1n0

**Comment by DarkBlade12** [comment]
Thanks for the report, the issues should have been fixed with the recent commits.
A new version will be uploaded to CurseForge soon.

**Comment by DarkBlade12** [comment]
Version 1.4.1 contains fixes for these bugs and has been uploaded to CurseForge.
