### ISSUE TITLE
Permissions seem broken. All commands given to everyone!

### ISSUE THREAD

**Issue by SmallSansSerif** [DarkBlade12/ItemSlotMachine#12]
Seems like all users can run commands including making new machines and the /coin give commands on new version 1.4.1

**Comment by SmallSansSerif** [comment]
1.4.1 fixed a ton of things for me but the perms seem to be broken.

**Comment by DarkBlade12** [comment]
Thanks for reporting, I could replicate this issue and will try to fix it and release an update over the course of the next days.

**Comment by SmallSansSerif** [comment]
If you figure out a work around or a way to deny perms in the meantime please let me know. Just had to disable for now. Thank goodness for a good player who alerted staff.

**Comment by DarkBlade12** [comment]
I have fixed this bug and uploaded the new version to CurseForge. It has been existing since 1.4.0 since I didn't change anything important related to permissions in version 1.4.1.
