### ISSUE TITLE
Wont Stop Winning!

### ISSUE THREAD

**Issue by asdfasdfasdfsadr** [DarkBlade12/ItemSlotMachine#5]
When someone wins, the winning sound, fireworks, ect. will go on until you break the machine. am i doing something wrong in the config?

**Comment by asdfasdfasdfsadr** [comment]
i dont have vault installed, but it says you dont have too

**Comment by DarkBlade12** [comment]
Are you using the current dev version for 1.8 or the older version for 1.7?
