### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by keough99** [DarkBlade12/ItemSlotMachine#7]
Hello
When I installed the plugin on my server I restarted it the server went up fine when I tried to connect it didn't let me connect to the server so I uninstalled the plugin and I was able to connect to the server again is this becuase my server is java 8?

**Comment by DarkBlade12** [comment]
ItemSlotMachine is compiled in Java 7 so it works absolutely fine with 8. It wouldn't work on a server running Java 6 for instance. Could you please look for errors/exceptions in your latest log file and post them here?

**Comment by keough99** [comment]
ill re instal it today so i can copy my log file

**Comment by keough99** [comment]
i reinstalled it and it workded it must have been a fluke thing with the server ill give you the logs anyways though so you can continue developing the plugin
http://pastebin.com/BisATf2p
